# Generated by Django 3.1.7 on 2021-05-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
